// General praise library: 500+ entries split across scenarios.
// Each entry hand-written to avoid mechanical repetition.
type Tone = 'enthusiastic' | 'growth_mindset' | 'humorous';
type Scenario =
  | 'perfect_score' | 'passed' | 'failed_encouragement'
  | 'streak_bonus' | 'level_up' | 'weakness_improved';

export const GENERAL_PRAISES: Array<{ scenario_type: Scenario; tone_type: Tone; content: string }> = [
  // ════════════════════════════════════════════════════════════
  // PASSED — 200 lines
  // ════════════════════════════════════════════════════════════
  // ── passed × enthusiastic ×70 ──
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '答得超棒！繼續保持這個氣勢！🌟' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '太厲害了！這個主題你已經掌握了！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '哇！這場真的太精彩了！👏' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '你看你今天有多會！再來一場！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '通關啦！蘑菇為你歡呼！🎉' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '勝利的滋味！記住這個感覺！🏆' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '你真的好強，蘑菇都崇拜你！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '一場漂亮的勝利！繼續加油！💪' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '看到你進步，蘑菇好感動！🥹' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '中文小達人就是你！🍄' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '你的腦袋今天超靈光！✨' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '這個成績配得上一杯珍珠奶茶！🧋' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '太準了！每一題都答得漂亮！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '通過了通過了！再戰一場吧！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '你今天的表現像金牌選手！🥇' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '蘑菇給你大大的擁抱！🤗' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '哇塞，這就是實力！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '你今天的腦力指數爆表！🧠' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '繼續這樣練下去，你會超強！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '你不只通過，還通過得很帥！😎' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '達標！蘑菇給你一個 high five！🙌' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '今天的你閃閃發光！⭐' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '你的努力被看見了！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '這場跟魔王戰一樣精彩！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '一個字：強！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '兩個字：超強！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '三個字：太強了！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '你是今天最閃亮的星星！🌠' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '蘑菇崇拜你的學習力！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '繼續打怪升級！⚔️' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '通過！下一題還會更厲害！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '你今天的表現滿分！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '蘑菇都跟著你進步了！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '答得漂亮！繼續衝！🏃' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '這場我給你 100 個讚！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '中文勇士就是你！⚔️' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '哇！你都答對了關鍵題！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '你的進步速度太誇張！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '蘑菇精靈為你旋轉！🌀' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '你越來越強了！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '通過得太漂亮，必須給掌聲！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '老師都會以你為傲！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '繼續這樣，目標就會達成！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '你是真的有用心！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '今天的答題節奏超棒！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '你看，努力是值得的！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '蘑菇給你一個金色獎牌！🥇' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '完美的一場！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '你今天簡直是中文天才！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '蘑菇精靈為你彈鋼琴！🎹' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '你已經追上小蘑菇的速度了！🏃‍♂️' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '通過！下次挑戰更難的吧！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '太厲害了，腦袋一定有渦輪！🚀' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '你今天答題就像在飛！✈️' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '通關通關通關！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '蘑菇給你蓋一個酷酷的章！🔖' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '你的進步藏不住啦！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '繼續這樣，你一定會更強！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '蘑菇精靈在森林裡幫你慶祝！🌳' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '你的學習力像火箭一樣！🚀' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '今天的你閃閃發光！✨' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '答對了！加倍開心！😄' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '蘑菇給你超大力的擊掌！🖐️' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '太強了，你一定有偷練！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '今天又拿下一場！繼續！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '你是國文寶藏！💎' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '通過！紅蘑菇與你同在！🍄' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '你的答案就像精準的弓箭！🏹' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '今天的你像超人！🦸' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '一氣呵成！太流暢了！' },
  { scenario_type: 'passed', tone_type: 'enthusiastic', content: '通關通關通關！繼續加油！' },
  // ── passed × growth_mindset ×70 ──
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你的努力有了成果！每一次練習都讓你變得更強。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你掌握了這個主題，這就是學習的力量。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '比起昨天的自己，你又前進一步了。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你的進步是看得見的。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '答得很穩，這代表你真的有理解。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '每一次的成功，都是下一次的基礎。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你看，努力是會被獎勵的。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你越來越會抓重點了。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '答對的關鍵題，代表你的思考很清楚。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '繼續這樣，下一個主題也會通過。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你已經知道怎麼面對這類題目了。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你今天的表現，配得上你的付出。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '進步是一點一點累積出來的，你做到了。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '答案來自思考，思考來自練習。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你的腦袋越來越靈活了。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '通過了，但更重要的是過程中的學習。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你已經建立起對這個主題的直覺。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '每一題答對都讓你更有信心。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你看，慢慢練習就會變強。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你的進步速度剛剛好，不要急。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '答對的那一刻，代表你真的懂了。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '保持這個學習節奏，你會更強。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你的答題策略越來越成熟。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '一場一場累積，你已經走了很遠。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你越來越敢挑戰難題了。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你的學習力像樹一樣，慢慢長高。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '答對是因為你願意思考。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你比上一場更穩定。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你的努力騙不了人。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你已經能舉一反三了。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '進步不在分數，而在你願意繼續。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你的中文越來越流暢。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '通過代表這個關卡你已經懂了。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你的閱讀速度也跟著進步了。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '繼續挑戰，繼續長大。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你已經比一個月前的自己強很多。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '答對的同時也學會了方法。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '蘑菇看得出你越來越用心。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '練習不會背叛你。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你的進步藏在每一道題裡。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '別忘了，過去的努力造就現在的你。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你今天的答題思路非常清楚。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你已經能看穿題目的陷阱了。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '繼續累積，你會越走越遠。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你的學習方法越來越聰明。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '通過了，但學習的旅程還沒結束。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你的努力會帶你去想去的地方。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你已經懂得耐心思考了。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '今天的你比昨天的你更有信心。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你已經把這類題目玩熟了。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '繼續這樣，下一個目標就在前方。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你的進步是真的，不是運氣。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你看，平常的累積派上用場了。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '通過代表你掌握了關鍵。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '蘑菇看到你的成長，覺得很開心。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '今天的你做出了正確的選擇。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '相信自己，你做得到。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你的腦袋越來越會分類資訊。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你的中文像河水一樣越走越遠。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '每一場通過，都是一個小里程碑。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你已經比剛開學時厲害太多了。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '保持好奇，會帶你走更遠。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '通過了，但收穫的是學會怎麼思考。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你已經知道下次該怎麼準備。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '蘑菇也跟著你一起學到很多。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '進步不是奇蹟，是你的選擇。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你的努力一定會在某天綻放。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '今天的你做了一件了不起的事：堅持。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '你越來越懂得分配時間了。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '通過了，蘑菇看見你成長的樣子。' },
  { scenario_type: 'passed', tone_type: 'growth_mindset', content: '繼續走，路會越來越寬。' },
  // ── passed × humorous ×60 ──
  { scenario_type: 'passed', tone_type: 'humorous', content: '哇！你簡直是語言天才！蘑菇為你驕傲！🍄' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '蘑菇精靈剛剛在森林裡跳起森巴！💃' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '你的大腦今天裝了渦輪引擎！🚀' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '紅蘑菇都怕你比牠還紅！' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '通過！蘑菇精靈賞你一袋金幣！💰' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '中文女神／男神就是你！😎' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '你的答題速度比閃電還快！⚡' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '答案們乖乖排隊讓你選！' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '蘑菇精靈打包送你獎章！🏅' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '通過得跟蘑菇湯一樣順！🍲' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '中文勇者！再給我一條龍來打！🐲' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '答對到蘑菇精靈差點滑倒！' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '你的腦袋是不是裝了字典？📖' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '答對！蘑菇給你一個微笑表情包！🤗' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '今天答題像吃蛋糕一樣輕鬆！🍰' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '你跟答案是好朋友！' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '蘑菇精靈剛剛拍手到手指疼！' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '你答題的樣子像在解魔方！🧩' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '錯題怪獸聽到你的名字都會逃跑！🐲💨' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '蘑菇精靈：「我不夠資格教你了！」' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '你的中文比夜市還熱鬧！' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '答得這麼漂亮，蘑菇要去做個慶祝蘑菇湯！🍄🍲' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '中文界的閃電俠！⚡' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '蘑菇精靈急著找朋友炫耀你！' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '你太強了，蘑菇都不好意思教你！' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '答題秒殺！太絲滑！' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '蘑菇給你一個 emoji 大禮包 🎁' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '你的進步速度像高鐵！🚄' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '通過！蘑菇給你一張免費珍奶券（誤）！' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '考試題目看到你都會發抖！' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '今天的答題像在演武俠片！🥋' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '蘑菇精靈：「我的徒弟太強！」' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '通過得讓老師笑開花！🌸' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '你的腦袋裡住著一個小老師！👩‍🏫' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '蘑菇精靈把你的名字寫在勝利牆上！' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '答對！蘑菇精靈表演空翻！🤸' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '你的答案精準到能射中蘑菇傘！🎯' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '通過！蘑菇給你超超超大讚！👍👍👍' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '答得太絲滑，連蘑菇都打結了！' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '蘑菇精靈在你頭上撒花！🌼' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '你的學習速度像 5G！📶' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '通過！蘑菇精靈給你蓋滿臉印章！💮' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '你的答題像功夫高手！🥋' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '答對！蘑菇尖叫到震動森林！🌳' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '小蘑菇看到你變超大蘑菇！🍄' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '答題就像吃 7-11 茶葉蛋一樣輕鬆！🥚' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '中文之神請接電話，是蘑菇打的！📞' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '你的進步比泡麵還快煮熟！🍜' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '通過！蘑菇精靈跑去通知朋友！' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '蘑菇給你一個香菇炒飯獎勵（誤）！🍳' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '你的答題就像放煙火！🎆' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '蘑菇精靈悄悄拜你為師！' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '答對！蘑菇把你寫進日記！📔' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '你進步到蘑菇都跟不上了！' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '通過得太順，蘑菇噴出蘑菇粉！💨' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '答題快到時鐘都來不及！⏰' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '蘑菇精靈：「徒弟出師了！」😭' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '你的中文比蘑菇還香！' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '答對！蘑菇給你一塊蘑菇巧克力！🍫' },
  { scenario_type: 'passed', tone_type: 'humorous', content: '通過！蘑菇給你一個香噴噴的擁抱！' },

  // ════════════════════════════════════════════════════════════
  // FAILED_ENCOURAGEMENT — 150 lines
  // ════════════════════════════════════════════════════════════
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '沒關係！失敗是成功的媽媽！下次一定可以！💪' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '蘑菇相信你下一場會更好！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '一場沒過沒關係，再戰！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '加油！你絕對可以的！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '蘑菇給你最大的鼓勵！🌟' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '繼續！你比想像中強大！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '蘑菇精靈為你加油！🍄' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '失敗是大魔王，但你會打敗它！⚔️' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '我相信你！再試一次！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '蘑菇給你一個鼓勵的擁抱！🤗' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '別放棄，你已經很努力了！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '下次絕對能贏！加油！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '蘑菇精靈幫你打氣！📣' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '你可以的，相信自己！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '再試一次，蘑菇陪你！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '加油加油！你超棒！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '蘑菇精靈相信你的潛力！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '別灰心，明天再戰！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '加油！你絕對是中文高手！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '繼續！失敗只是過程！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '蘑菇給你滿滿正能量！⚡' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '再來！蘑菇看好你！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '加油！下次絕對通關！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '蘑菇精靈絕對相信你！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '別氣餒，你已經很厲害！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '蘑菇精靈：「我相信你！」' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '加油！我們一起打怪！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '一次失敗算什麼，蘑菇陪你！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '蘑菇給你超大份信心！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '繼續加油！你會更強！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '別放棄，蘑菇與你同在！🍄' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '加油！再來一次！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '失敗只是暫時的，加油！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '蘑菇精靈為你歡呼！👏' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '相信過程，相信自己！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '加油！每一次嘗試都重要！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '蘑菇相信你的努力會有回報！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '別放棄，下次絕對贏！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '蘑菇給你一個高五！🖐️' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '加油！你已經是最棒的！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '再試一次，你會發現自己變強！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '蘑菇精靈相信你能做到！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '加油！蘑菇給你愛心！💚' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '別灰心，下一場更精彩！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '繼續努力，你會成功的！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '加油！每一步都是成長！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '蘑菇相信你的潛力無限！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '別放棄！蘑菇陪你戰鬥！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '加油！你可以的！' },
  { scenario_type: 'failed_encouragement', tone_type: 'enthusiastic', content: '蘑菇精靈：「重新出發！」' },
  // ── growth_mindset ×60 ──
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '這次的錯誤是學習的機會。看看哪裡可以做得更好！' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '錯誤是大腦在長肌肉，繼續！' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '答錯沒關係，記住為什麼就好。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '一次沒過，代表還有可以學的地方。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '失敗不是終點，是下一次起點。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '看一下錯題怪獸，下次就不會錯了。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '每次錯誤都讓你更靠近正確。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '失敗教給你的，比成功多。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '你願意嘗試，就已經贏了一半。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '錯了再來，這就是學習。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '答錯後想一下原因，這就是進步。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '今天的錯誤，是明天的記憶點。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '不會的就學，學會了就用。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '失敗是學習地圖上的標記。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '錯題會變成你最珍貴的筆記。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '每一次答錯都讓你的腦袋更聰明。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '答錯比答對讓你學更多。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '不要怕錯，只怕不嘗試。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '錯誤是成長的養分。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '你已經比剛剛的自己更接近答案。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '從錯誤中學到的，最深刻。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '下一次，你會做得更好。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '答錯沒有不好，能改進才是真本事。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '錯一題沒事，繼續走就好。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '你會發現，錯題後的進步最快。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '今天沒過，不代表永遠沒過。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '你的努力會在某一場開花。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '答錯是大腦正在重新組裝。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '失敗只是進步的暫停鍵。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '錯誤讓你更了解自己。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '每一次嘗試都很有價值。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '不會就學，學了就會。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '答錯沒關係，回去看一下答案就好。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '你的腦袋正在學新東西。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '失敗一次，就少錯一次。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '不要怕失敗，只怕不思考。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '錯了再來，你會更穩。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '錯誤是學習中最誠實的朋友。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '你已經比第一次練習進步很多。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '答錯沒事，下次再答對就贏了。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '錯題庫會帶你進步。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '今天的錯誤教你怎麼面對下次。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '不要放棄，思考是寶藏。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '錯誤讓你看見可以改進的地方。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '失敗教給你的，是書本沒有的。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '你正在累積經驗值。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '答錯後願意重來，最珍貴。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '下一次，你會記得這個錯誤的提醒。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '從哪裡跌倒，就從哪裡站起來。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '錯誤教你的事，蘑菇都記下了。' },
  { scenario_type: 'failed_encouragement', tone_type: 'growth_mindset', content: '每個錯誤都是一塊踏腳石。' },
  // ── humorous ×40 ──
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '哎呀，蘑菇也需要雨水才能長大，再試一次吧！☔' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '題目剛剛打了一個小哈欠，下次絕對抓到牠！😴' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '蘑菇精靈說：「對手只是逃跑得快了一點！」' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '別擔心，蘑菇也曾不會分注音！' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '錯題怪獸在偷笑，但牠不知道你下次會贏！🐲' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '蘑菇精靈悄悄遞給你一張免費補考券（誤）！🎟️' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '別氣！蘑菇給你一份蘑菇湯安慰你！🍲' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '題目跟你玩躲貓貓，下次找到牠！👀' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '蘑菇拍拍你的肩膀，繼續走！' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '別怕，蘑菇精靈也常常迷路！' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '答案在轉角處傻笑，下次找到牠！😀' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '蘑菇精靈：「下次牠絕對沒位置藏！」' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '錯誤是蘑菇的好朋友，慢慢來！' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '蘑菇精靈遞給你一杯加倍珍奶！🧋' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '答案在玩捉迷藏，蘑菇陪你找！' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '別擔心，題目剛剛喝太多咖啡了！☕' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '蘑菇精靈悄悄打了一個耳光給錯題！' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '錯題怪獸暫時贏了，但等著瞧！⚔️' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '蘑菇給你一個哈哈一笑！😄' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '答錯沒事，蘑菇精靈一起被罵！' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '蘑菇精靈：「題目運氣好！下次換我們！」' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '答錯了，但你的努力被蘑菇 100% 收下！' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '錯一題，下次跨兩步！' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '蘑菇精靈安慰你：「我也常常忘記答案！」' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '錯題說：「我是來幫你的！」🐲' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '蘑菇給你一張迷你勝利圖！🏅' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '今天沒過，蘑菇陪你練功！🥋' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '蘑菇精靈：「先休息，再戰！」' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '別氣，蘑菇給你蓋一個「快樂章」！😊' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '答題像爬山，這次只是爬到一半！🏞️' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '蘑菇精靈悄悄把錯題收進口袋！' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '錯題怪獸笑著等你練功復仇！' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '答錯沒事，蘑菇給你一片香菇貼紙！' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '蘑菇精靈拍拍蘑菇頭，沒事的！' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '今天的題目像隻調皮的貓，下次抓住牠！🐱' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '蘑菇精靈：「練習就會抓到節奏！」' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '錯題暫時得意，但你會打敗牠！' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '蘑菇給你一個輕鬆的笑容！😆' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '錯題逃跑得快，下次蘑菇幫你伸腳！' },
  { scenario_type: 'failed_encouragement', tone_type: 'humorous', content: '別氣，蘑菇精靈陪你再衝一次！' },

  // ════════════════════════════════════════════════════════════
  // PERFECT_SCORE — 50 lines
  // ════════════════════════════════════════════════════════════
  { scenario_type: 'perfect_score', tone_type: 'enthusiastic', content: '滿分！滿分！你是今天最厲害的國語文勇士！🏆🎉' },
  { scenario_type: 'perfect_score', tone_type: 'enthusiastic', content: '100 分！蘑菇都跪了！' },
  { scenario_type: 'perfect_score', tone_type: 'enthusiastic', content: '完美！這場讓老師都鼓掌！👏' },
  { scenario_type: 'perfect_score', tone_type: 'enthusiastic', content: '滿分達成！蘑菇給你王冠！👑' },
  { scenario_type: 'perfect_score', tone_type: 'enthusiastic', content: '神級表現！太強！⭐⭐⭐' },
  { scenario_type: 'perfect_score', tone_type: 'enthusiastic', content: '滿分！蘑菇給你最大讚！👍👍👍' },
  { scenario_type: 'perfect_score', tone_type: 'enthusiastic', content: '完美無瑕！你的中文已封神！' },
  { scenario_type: 'perfect_score', tone_type: 'enthusiastic', content: '蘑菇精靈為你舉辦慶功宴！🎊' },
  { scenario_type: 'perfect_score', tone_type: 'enthusiastic', content: '100 分！你今天是 MVP！🥇' },
  { scenario_type: 'perfect_score', tone_type: 'enthusiastic', content: '蘑菇精靈：「徒弟超越師傅！」😭' },
  { scenario_type: 'perfect_score', tone_type: 'enthusiastic', content: '滿分一場，蘑菇給你獎盃！🏆' },
  { scenario_type: 'perfect_score', tone_type: 'enthusiastic', content: '完美！太強了！必須截圖留念！📸' },
  { scenario_type: 'perfect_score', tone_type: 'enthusiastic', content: '100 分！蘑菇精靈為你立傳！📜' },
  { scenario_type: 'perfect_score', tone_type: 'enthusiastic', content: '滿分滿分！你的字典是金的！📖' },
  { scenario_type: 'perfect_score', tone_type: 'enthusiastic', content: '蘑菇給你蘑菇貴族頭銜！🍄👑' },
  { scenario_type: 'perfect_score', tone_type: 'enthusiastic', content: '完美！每一題都答得漂亮！' },
  { scenario_type: 'perfect_score', tone_type: 'enthusiastic', content: '滿分！蘑菇精靈拜你為神！🙏' },
  { scenario_type: 'perfect_score', tone_type: 'enthusiastic', content: '100 分！要不要去報名國語比賽？' },
  { scenario_type: 'perfect_score', tone_type: 'enthusiastic', content: '蘑菇精靈：「我等到滿分這一天！」' },
  { scenario_type: 'perfect_score', tone_type: 'enthusiastic', content: '完美！蘑菇給你蘑菇神壇！⛩️' },
  // ── growth_mindset ×15 ──
  { scenario_type: 'perfect_score', tone_type: 'growth_mindset', content: '完美！這說明你真的掌握了這個主題，繼續探索新知識！' },
  { scenario_type: 'perfect_score', tone_type: 'growth_mindset', content: '滿分代表你已經把這個主題吃透了。' },
  { scenario_type: 'perfect_score', tone_type: 'growth_mindset', content: '100 分背後是你的累積，這很珍貴。' },
  { scenario_type: 'perfect_score', tone_type: 'growth_mindset', content: '完美的一場！這就是長時間練習的成果。' },
  { scenario_type: 'perfect_score', tone_type: 'growth_mindset', content: '滿分讓你知道：努力是有用的。' },
  { scenario_type: 'perfect_score', tone_type: 'growth_mindset', content: '這場滿分證明你可以挑戰更難的題目了。' },
  { scenario_type: 'perfect_score', tone_type: 'growth_mindset', content: '完美！但更棒的是你享受過程的態度。' },
  { scenario_type: 'perfect_score', tone_type: 'growth_mindset', content: '滿分是平常累積的結果。' },
  { scenario_type: 'perfect_score', tone_type: 'growth_mindset', content: '100 分！下一個目標：保持這個專注度。' },
  { scenario_type: 'perfect_score', tone_type: 'growth_mindset', content: '滿分代表你已經能舉一反三。' },
  { scenario_type: 'perfect_score', tone_type: 'growth_mindset', content: '完美！這是你選擇繼續練習的回報。' },
  { scenario_type: 'perfect_score', tone_type: 'growth_mindset', content: '滿分一次，下次可以挑戰新主題。' },
  { scenario_type: 'perfect_score', tone_type: 'growth_mindset', content: '100 分！但學習的真正禮物是這個過程。' },
  { scenario_type: 'perfect_score', tone_type: 'growth_mindset', content: '完美！你的中文穩穩往上走。' },
  { scenario_type: 'perfect_score', tone_type: 'growth_mindset', content: '滿分讓你看見：你比想像中更強。' },
  // ── humorous ×15 ──
  { scenario_type: 'perfect_score', tone_type: 'humorous', content: '滿分！蘑菇精靈跑去告訴整個森林！🌲' },
  { scenario_type: 'perfect_score', tone_type: 'humorous', content: '100 分！蘑菇給你蘑菇拉麵升級套餐！🍜' },
  { scenario_type: 'perfect_score', tone_type: 'humorous', content: '完美！蘑菇精靈感動到滴出蘑菇汁！🥹' },
  { scenario_type: 'perfect_score', tone_type: 'humorous', content: '滿分！老師都驚呆了！😲' },
  { scenario_type: 'perfect_score', tone_type: 'humorous', content: '100 分！蘑菇精靈幫你弄一頂蘑菇皇冠！👑🍄' },
  { scenario_type: 'perfect_score', tone_type: 'humorous', content: '完美！蘑菇精靈把你的名字寫滿天空！☁️' },
  { scenario_type: 'perfect_score', tone_type: 'humorous', content: '滿分！蘑菇給你一個香菇仙子吻！💋' },
  { scenario_type: 'perfect_score', tone_type: 'humorous', content: '100 分！蘑菇精靈直接退休讓你接位！' },
  { scenario_type: 'perfect_score', tone_type: 'humorous', content: '完美！蘑菇給你蘑菇盛宴！🍄🍽️' },
  { scenario_type: 'perfect_score', tone_type: 'humorous', content: '滿分！蘑菇精靈宣布今天是「你之日」！🎉' },
  { scenario_type: 'perfect_score', tone_type: 'humorous', content: '100 分！蘑菇給你超大份蘑菇炒飯！🍳' },
  { scenario_type: 'perfect_score', tone_type: 'humorous', content: '滿分！蘑菇精靈跑去買蘑菇蛋糕！🎂' },
  { scenario_type: 'perfect_score', tone_type: 'humorous', content: '完美！蘑菇精靈跪著遞給你獎牌！🥇' },
  { scenario_type: 'perfect_score', tone_type: 'humorous', content: '100 分！蘑菇精靈急著拍照存證！📷' },
  { scenario_type: 'perfect_score', tone_type: 'humorous', content: '滿分！蘑菇精靈跳起森巴慶祝！💃' },

  // ════════════════════════════════════════════════════════════
  // STREAK_BONUS — 50 lines
  // ════════════════════════════════════════════════════════════
  { scenario_type: 'streak_bonus', tone_type: 'enthusiastic', content: '連續練習！你的毅力讓蘑菇精靈感動不已！🔥🔥' },
  { scenario_type: 'streak_bonus', tone_type: 'enthusiastic', content: '連勝！火焰越燒越旺！🔥' },
  { scenario_type: 'streak_bonus', tone_type: 'enthusiastic', content: '又一天通過！連勝持續中！' },
  { scenario_type: 'streak_bonus', tone_type: 'enthusiastic', content: '連續打卡！蘑菇給你大大讚！👍' },
  { scenario_type: 'streak_bonus', tone_type: 'enthusiastic', content: '你的連勝表讓蘑菇眼花！✨' },
  { scenario_type: 'streak_bonus', tone_type: 'enthusiastic', content: '連續通過！太穩了！' },
  { scenario_type: 'streak_bonus', tone_type: 'enthusiastic', content: '你已經養成超棒的學習習慣！' },
  { scenario_type: 'streak_bonus', tone_type: 'enthusiastic', content: '蘑菇精靈為你的連勝歡呼！🎉' },
  { scenario_type: 'streak_bonus', tone_type: 'enthusiastic', content: '一天接一天，你太強了！' },
  { scenario_type: 'streak_bonus', tone_type: 'enthusiastic', content: '連勝大師就是你！' },
  { scenario_type: 'streak_bonus', tone_type: 'enthusiastic', content: '蘑菇給你的火焰更大了！🔥🔥🔥' },
  { scenario_type: 'streak_bonus', tone_type: 'enthusiastic', content: '連續挑戰！不愧是中文勇士！⚔️' },
  { scenario_type: 'streak_bonus', tone_type: 'enthusiastic', content: '蘑菇精靈幫你慶祝連勝！' },
  { scenario_type: 'streak_bonus', tone_type: 'enthusiastic', content: '繼續這個節奏！太棒了！' },
  { scenario_type: 'streak_bonus', tone_type: 'enthusiastic', content: '連勝中！每天都看得到你的努力！' },
  { scenario_type: 'streak_bonus', tone_type: 'enthusiastic', content: '蘑菇給你連勝徽章！🏅' },
  { scenario_type: 'streak_bonus', tone_type: 'enthusiastic', content: '連勝紀錄又刷新！恭喜！' },
  { scenario_type: 'streak_bonus', tone_type: 'enthusiastic', content: '蘑菇精靈：「這毅力我服了！」' },
  { scenario_type: 'streak_bonus', tone_type: 'enthusiastic', content: '繼續燃燒，火焰勇士！🔥' },
  { scenario_type: 'streak_bonus', tone_type: 'enthusiastic', content: '連勝氣勢無人能擋！' },
  // growth_mindset ×15
  { scenario_type: 'streak_bonus', tone_type: 'growth_mindset', content: '連續練習是大腦最喜歡的禮物。' },
  { scenario_type: 'streak_bonus', tone_type: 'growth_mindset', content: '每天一點點，累積起來就是大進步。' },
  { scenario_type: 'streak_bonus', tone_type: 'growth_mindset', content: '你已經把學習變成日常的一部分。' },
  { scenario_type: 'streak_bonus', tone_type: 'growth_mindset', content: '連勝是你的時間在說話。' },
  { scenario_type: 'streak_bonus', tone_type: 'growth_mindset', content: '不間斷是最有效的學習方法。' },
  { scenario_type: 'streak_bonus', tone_type: 'growth_mindset', content: '你的習慣比天賦更值得驕傲。' },
  { scenario_type: 'streak_bonus', tone_type: 'growth_mindset', content: '連勝代表你已經建立節奏。' },
  { scenario_type: 'streak_bonus', tone_type: 'growth_mindset', content: '今天的堅持，是明天的實力。' },
  { scenario_type: 'streak_bonus', tone_type: 'growth_mindset', content: '每一天的累積都很有意義。' },
  { scenario_type: 'streak_bonus', tone_type: 'growth_mindset', content: '連勝讓你的大腦穩定成長。' },
  { scenario_type: 'streak_bonus', tone_type: 'growth_mindset', content: '你的努力是看得見的軌跡。' },
  { scenario_type: 'streak_bonus', tone_type: 'growth_mindset', content: '習慣的力量超過天份。' },
  { scenario_type: 'streak_bonus', tone_type: 'growth_mindset', content: '連勝是長期主義的勝利。' },
  { scenario_type: 'streak_bonus', tone_type: 'growth_mindset', content: '你已經練成了學習肌肉。' },
  { scenario_type: 'streak_bonus', tone_type: 'growth_mindset', content: '小步前進，最後走最遠。' },
  // humorous ×15
  { scenario_type: 'streak_bonus', tone_type: 'humorous', content: '蘑菇精靈幫你續火，火焰越燒越大！🔥' },
  { scenario_type: 'streak_bonus', tone_type: 'humorous', content: '連勝！蘑菇精靈幫你開派對！🎉' },
  { scenario_type: 'streak_bonus', tone_type: 'humorous', content: '連勝中，蘑菇給你蘑菇火鍋！🍲' },
  { scenario_type: 'streak_bonus', tone_type: 'humorous', content: '連勝！蘑菇精靈直接被你嚇到！' },
  { scenario_type: 'streak_bonus', tone_type: 'humorous', content: '你的連勝表比蘑菇還高了！' },
  { scenario_type: 'streak_bonus', tone_type: 'humorous', content: '蘑菇精靈：「你是火神嗎？」🔥' },
  { scenario_type: 'streak_bonus', tone_type: 'humorous', content: '連勝！蘑菇給你發超大紅包！🧧' },
  { scenario_type: 'streak_bonus', tone_type: 'humorous', content: '蘑菇精靈拿著火炬幫你接力！' },
  { scenario_type: 'streak_bonus', tone_type: 'humorous', content: '連勝！蘑菇精靈感動到哭出蘑菇水！💧' },
  { scenario_type: 'streak_bonus', tone_type: 'humorous', content: '蘑菇給你蘑菇旗一面，慶祝連勝！🚩' },
  { scenario_type: 'streak_bonus', tone_type: 'humorous', content: '連勝！蘑菇精靈報名你當市長！😆' },
  { scenario_type: 'streak_bonus', tone_type: 'humorous', content: '蘑菇精靈：「連勝幾天我都嫉妒了！」' },
  { scenario_type: 'streak_bonus', tone_type: 'humorous', content: '連勝中！蘑菇給你一個香菇火把！' },
  { scenario_type: 'streak_bonus', tone_type: 'humorous', content: '連勝！蘑菇精靈把你寫進神話！📖' },
  { scenario_type: 'streak_bonus', tone_type: 'humorous', content: '蘑菇精靈幫你買了煙火慶祝！🎆' },

  // ════════════════════════════════════════════════════════════
  // LEVEL_UP — 30 lines
  // ════════════════════════════════════════════════════════════
  { scenario_type: 'level_up', tone_type: 'enthusiastic', content: '升級啦！歡迎來到新的等級！更大的挑戰等著你！⬆️✨' },
  { scenario_type: 'level_up', tone_type: 'enthusiastic', content: '升級！你的角色變強了！⚔️' },
  { scenario_type: 'level_up', tone_type: 'enthusiastic', content: '又升一級！蘑菇精靈為你歡呼！' },
  { scenario_type: 'level_up', tone_type: 'enthusiastic', content: '等級提升！新技能解鎖！🎮' },
  { scenario_type: 'level_up', tone_type: 'enthusiastic', content: '蘑菇給你升級徽章！🎖️' },
  { scenario_type: 'level_up', tone_type: 'enthusiastic', content: '升級！你變得更強壯！💪' },
  { scenario_type: 'level_up', tone_type: 'enthusiastic', content: '上去了！下一關等你！' },
  { scenario_type: 'level_up', tone_type: 'enthusiastic', content: '升級！蘑菇給你超大讚！👍' },
  { scenario_type: 'level_up', tone_type: 'enthusiastic', content: '等級提升！繼續挑戰！' },
  { scenario_type: 'level_up', tone_type: 'enthusiastic', content: '蘑菇精靈大喊：「升級啦！」📣' },
  // growth_mindset ×10
  { scenario_type: 'level_up', tone_type: 'growth_mindset', content: '升級代表你又向前邁了一大步。' },
  { scenario_type: 'level_up', tone_type: 'growth_mindset', content: '新的等級，新的視野。' },
  { scenario_type: 'level_up', tone_type: 'growth_mindset', content: '你的成長被系統記住了。' },
  { scenario_type: 'level_up', tone_type: 'growth_mindset', content: '升級是長期累積的結果。' },
  { scenario_type: 'level_up', tone_type: 'growth_mindset', content: '新等級，新挑戰，新機會。' },
  { scenario_type: 'level_up', tone_type: 'growth_mindset', content: '升級提醒你：努力是被看見的。' },
  { scenario_type: 'level_up', tone_type: 'growth_mindset', content: '走到這裡的你，已經很厲害。' },
  { scenario_type: 'level_up', tone_type: 'growth_mindset', content: '每一級都是你選擇繼續的回報。' },
  { scenario_type: 'level_up', tone_type: 'growth_mindset', content: '新的等級是穩定學習的證明。' },
  { scenario_type: 'level_up', tone_type: 'growth_mindset', content: '升級，但更值得驕傲的是過程。' },
  // humorous ×10
  { scenario_type: 'level_up', tone_type: 'humorous', content: '升級！蘑菇給你蘑菇加裝甲！🛡️' },
  { scenario_type: 'level_up', tone_type: 'humorous', content: '升級！蘑菇精靈悄悄拍照存證！📷' },
  { scenario_type: 'level_up', tone_type: 'humorous', content: '升級！蘑菇給你蘑菇火箭發射！🚀' },
  { scenario_type: 'level_up', tone_type: 'humorous', content: '升級！蘑菇精靈：「徒弟厲害了！」' },
  { scenario_type: 'level_up', tone_type: 'humorous', content: '升級！蘑菇給你蘑菇皇冠！👑' },
  { scenario_type: 'level_up', tone_type: 'humorous', content: '升級！蘑菇精靈幫你買蘑菇蛋糕！🎂' },
  { scenario_type: 'level_up', tone_type: 'humorous', content: '升級！蘑菇精靈跳森巴！💃' },
  { scenario_type: 'level_up', tone_type: 'humorous', content: '升級！蘑菇給你蘑菇放煙火！🎆' },
  { scenario_type: 'level_up', tone_type: 'humorous', content: '升級！蘑菇精靈拍翻桌子慶祝！🥳' },
  { scenario_type: 'level_up', tone_type: 'humorous', content: '升級！蘑菇精靈跑去發紅包！🧧' },

  // ════════════════════════════════════════════════════════════
  // WEAKNESS_IMPROVED — 20 lines
  // ════════════════════════════════════════════════════════════
  { scenario_type: 'weakness_improved', tone_type: 'growth_mindset', content: '弱點變優點，這就是進步的證據。' },
  { scenario_type: 'weakness_improved', tone_type: 'growth_mindset', content: '你曾經卡關的題型現在答對了，太棒了。' },
  { scenario_type: 'weakness_improved', tone_type: 'growth_mindset', content: '你已經克服了之前的弱點。' },
  { scenario_type: 'weakness_improved', tone_type: 'growth_mindset', content: '記得當初不會的題目嗎？現在你會了。' },
  { scenario_type: 'weakness_improved', tone_type: 'growth_mindset', content: '弱點變強項，你做到了。' },
  { scenario_type: 'weakness_improved', tone_type: 'growth_mindset', content: '進步看得見，你超棒。' },
  { scenario_type: 'weakness_improved', tone_type: 'growth_mindset', content: '你選擇正面面對弱點，這很勇敢。' },
  { scenario_type: 'weakness_improved', tone_type: 'growth_mindset', content: '錯題怪獸被你淨化了！' },
  { scenario_type: 'weakness_improved', tone_type: 'growth_mindset', content: '練習真的有用，你看見了嗎？' },
  { scenario_type: 'weakness_improved', tone_type: 'growth_mindset', content: '弱點變優點，是學習最開心的時刻。' },
  { scenario_type: 'weakness_improved', tone_type: 'enthusiastic', content: '弱項翻身！太精彩！⭐' },
  { scenario_type: 'weakness_improved', tone_type: 'enthusiastic', content: '逆風變順風！蘑菇給你大讚！👍' },
  { scenario_type: 'weakness_improved', tone_type: 'enthusiastic', content: '錯題怪獸被打敗！🐲💥' },
  { scenario_type: 'weakness_improved', tone_type: 'enthusiastic', content: '原本不會，現在拿手！太強！' },
  { scenario_type: 'weakness_improved', tone_type: 'enthusiastic', content: '蘑菇精靈幫你貼上「克服弱點」獎章！🏅' },
  { scenario_type: 'weakness_improved', tone_type: 'humorous', content: '錯題怪獸：「我輸了……」🐲💧' },
  { scenario_type: 'weakness_improved', tone_type: 'humorous', content: '弱點被你 KO，蘑菇精靈鼓掌！👏' },
  { scenario_type: 'weakness_improved', tone_type: 'humorous', content: '錯題怪獸搬家了，你勝利了！' },
  { scenario_type: 'weakness_improved', tone_type: 'humorous', content: '弱點怪獸開始閃避你，太強了！' },
  { scenario_type: 'weakness_improved', tone_type: 'humorous', content: '蘑菇精靈悄悄記下：徒弟克服弱點！' },
];
