// 50 SEN-friendly encouragements. Tone: warm, paced, no clinical terms.
// Never references "slow", "special", or "disability". Frontend labels these
// as "輕鬆學習模式" praise.
type Tone = 'enthusiastic' | 'growth_mindset' | 'humorous';

export const SEN_PRAISES: Array<{ tone_type: Tone; content: string }> = [
  // growth_mindset (warm, paced) ×30
  { tone_type: 'growth_mindset', content: '按你的節奏走，每一步都算數。' },
  { tone_type: 'growth_mindset', content: '今天比昨天多認識一個字，太棒了。' },
  { tone_type: 'growth_mindset', content: '想了好久才答出來，那是用腦的證明。' },
  { tone_type: 'growth_mindset', content: '答錯沒關係，記住這個感覺就好。' },
  { tone_type: 'growth_mindset', content: '深呼吸，再來一次，沒有壓力。' },
  { tone_type: 'growth_mindset', content: '你比剛剛更靠近答案了，繼續。' },
  { tone_type: 'growth_mindset', content: '慢慢看題目，你會看出來的。' },
  { tone_type: 'growth_mindset', content: '一步一步來，蘑菇精靈陪著你。' },
  { tone_type: 'growth_mindset', content: '休息一下也是學習的一部分。' },
  { tone_type: 'growth_mindset', content: '你今天願意學，已經非常厲害了。' },
  { tone_type: 'growth_mindset', content: '記得呼吸，題目不會跑掉。' },
  { tone_type: 'growth_mindset', content: '答案就在你的腦袋裡，再想一下。' },
  { tone_type: 'growth_mindset', content: '不需要跟誰比，做你自己就好。' },
  { tone_type: 'growth_mindset', content: '你比昨天的自己更厲害了。' },
  { tone_type: 'growth_mindset', content: '每一個字都讀懂了，這就是進步。' },
  { tone_type: 'growth_mindset', content: '只要再試一次，就是新的開始。' },
  { tone_type: 'growth_mindset', content: '今天能做到這裡，已經很棒。' },
  { tone_type: 'growth_mindset', content: '不用急，慢慢來就好。' },
  { tone_type: 'growth_mindset', content: '你願意思考，就是學習的開始。' },
  { tone_type: 'growth_mindset', content: '看到題目願意讀，就是勇氣。' },
  { tone_type: 'growth_mindset', content: '走得慢一點，看得更清楚。' },
  { tone_type: 'growth_mindset', content: '每個小進步都值得開心。' },
  { tone_type: 'growth_mindset', content: '答對或答錯，都是練習。' },
  { tone_type: 'growth_mindset', content: '你今天的努力，蘑菇都記得。' },
  { tone_type: 'growth_mindset', content: '溫柔地對待自己，這也是學習。' },
  { tone_type: 'growth_mindset', content: '今天答完一題就很好。' },
  { tone_type: 'growth_mindset', content: '想得到答案，是因為你有在想。' },
  { tone_type: 'growth_mindset', content: '只要你開始，就已經贏了。' },
  { tone_type: 'growth_mindset', content: '錯了就再來，不會被罵。' },
  { tone_type: 'growth_mindset', content: '一題一題慢慢來，沒人在比賽。' },
  // enthusiastic (warm cheer) ×12
  { tone_type: 'enthusiastic', content: '你願意再試一次，就是最大的進步！🌟' },
  { tone_type: 'enthusiastic', content: '小蘑菇看到你今天認真的眼神！🍄' },
  { tone_type: 'enthusiastic', content: '你做到了！繼續用自己的節奏！💛' },
  { tone_type: 'enthusiastic', content: '今天真的好棒，蘑菇精靈為你開心！🌈' },
  { tone_type: 'enthusiastic', content: '完成一題就值得鼓掌！👏' },
  { tone_type: 'enthusiastic', content: '看到你思考的樣子，超酷！' },
  { tone_type: 'enthusiastic', content: '你今天願意學，已經贏了！' },
  { tone_type: 'enthusiastic', content: '蘑菇給你一個大大的笑臉！😊' },
  { tone_type: 'enthusiastic', content: '你比想像中更勇敢！' },
  { tone_type: 'enthusiastic', content: '今天的你超讚！' },
  { tone_type: 'enthusiastic', content: '小蘑菇給你愛心抱抱！💚' },
  { tone_type: 'enthusiastic', content: '你看，你做到了！' },
  // humorous (gentle, never silly at user's expense) ×8
  { tone_type: 'humorous', content: '哎呀，這題會跟你捉迷藏，下次抓到它！' },
  { tone_type: 'humorous', content: '蘑菇精靈剛剛打了個小哈欠，因為太放鬆了！' },
  { tone_type: 'humorous', content: '題目笑著等你回來呢！' },
  { tone_type: 'humorous', content: '答案在角落偷看你，再找一下！' },
  { tone_type: 'humorous', content: '小蘑菇陪你慢慢走，不會比快的！' },
  { tone_type: 'humorous', content: '蘑菇精靈打了個小噴嚏，要不要再試一題？' },
  { tone_type: 'humorous', content: '今天的題目跟你說「下次再見」！' },
  { tone_type: 'humorous', content: '蘑菇給你一個迷你勝利舞！💃' },
];
